let sampleJSON =`[
    {
        "name":"Emre",
        "surname":"AYDIN",
    },
    {
        "name":"Mert",
        "surname":"AYDIN",
    },
    {
        "name":"Ayşegül",
        "surname":"AYDIN",
    },
    {
        "name":"Mehmet",
        "surname":"AYDIN",
    }
]`
le
console.log(sampleJSON);